### ISSUE TITLE
Typing too fast.

### ISSUE THREAD

**Issue by khazhyk** [Hexaweeb/Discord_Scripts#1]
A typing indicator lasts 10 seconds, so you only need to send it every ~8-9 seconds for a consistent typing indication.

re: https://github.com/Hexaweeb/Discord_Scripts/blob/master/discordtype.py#L15

Also: why?

**Comment by Hexaweeb** [comment]
In my experience the typing indicator lasting ten seconds wasn't the case. At most I counted to five. That being said, you can be just as obnoxious setting it to 8-10 second intervals, I see no real problem with that.

As far as "why", I don't really know. I got bored and realized that Discord client is based on Chromium, and that pressing CTRL+SHIFT+I actually opens up Chromium's dev tools, including network requests. I noticed that typing was being sent whenever I began to type, so I thought "why not" and made this. I messed around with it in my server and a friend asked me to push it so I did.
